name: SMM
on:
  push:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Copy file via SSH password
        uses: appleboy/scp-action@v1
        with:
          host: ${{secrets.EC2_HOST}}
          username: ${{secrets.USERNAME}}
          key: ${{secrets.KEY}}
          port: 22
          source: "."
          target: "var/www/html"
